name: testman

on: [push]

jobs:
  run-unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github Source
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 18.18.2

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test
    
